repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: []
        files: ^src/

  - repo: local
    hooks:
      - id: lint
        name: npm lint
        entry: npm lint
        language: system
        files: ^src/
        exclude_types: [csv, json, css, scss]
        exclude: ^src/assets/
  - repo: 
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^frontend\/[^\/]+
        args: [--config, .prettierrc,--write]
        additional_dependencies:
          - prettier
          - prettier-plugin-svelte
