name: Lint frontend
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --frozen-lockfile --silent
        env:
          CI: true
      - uses: pre-commit/action@v3.0.1
      - name: Build
        run: bun build
        env:
          CI: true
