name: Lint frontend
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: '18.x' # set this to the node version to use

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: bun install --frozen-lockfile --silent
        env:
          CI: true
      - name: Lint
        run: bunx pre-commit run -a
        env:
          CI: true
      - name: Build
        run: bun build
        env:
          CI: true
